### ISSUE TITLE
Switch to a newer build system

### ISSUE THREAD

**Issue by dquigley533** [dquigley533/hs_alkane#8]
Currently hs_alkane build system relies on numpy.distutils which is deprecated and has been removed from Python version 3.12 and newer. 

https://numpy.org/doc/stable/reference/distutils.html

Probably long past due to switch to something newer.

**Comment by dquigley533** [comment]
Implemented with https://github.com/dquigley533/hs_alkane/commit/ab034bac237e9eeafc7bb967fb004925336ac3c2. 

Fails to import on MacOS:

```
>>> import hs_alkane as mdl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxxxx/Library/Python/3.12/lib/python/site-packages/hs_alkane/__init__.py", line 7, in <module>
    from ._alkane import *
ImportError: dlopen(/Users/xxxxx/Library/Python/3.12/lib/python/site-packages/hs_alkane/_alkane.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/libgfortran.5.dylib
  Referenced from: <9A12420E-CC79-3071-8F8E-259A631AE1C3> /Users/xxxxx/Library/Python/3.12/lib/python/site-packages/hs_alkane/_alkane.cpython-312-darwin.so
  Reason: no LC_RPATH's found
```
Working fine on Linux.
